services:
  shipping:
    build: .
    container_name: shipping
    environment:
      - SERVER_PORT=8282
    ports:
      - "8282:8282"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true