services:
  shipping:
    build: .
    container_name: shipping
    environment:
      - SERVER_PORT=8484
    ports:
      - "8484:8484"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true